security:
    # Configuration du hashage des mots de passe
    password_hashers:
        App\Entity\Employee:
            algorithm: auto


    # Définition de la hiérarchie des rôles
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_VETERINARY, ROLE_KEEPER]
        ROLE_VETERINARY: [ROLE_USER]
        ROLE_KEEPER: [ROLE_USER]

    # Configuration du fournisseur d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Employee
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/ 
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\LoginFormAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: /dashboard
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true
            custom_authenticator: App\Security\LoginFormAuthenticator

    # Gestion des accès aux routes
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/veterinary, roles: ROLE_VETERINARY }
        - { path: ^/keeper, roles: ROLE_KEEPER }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
